services:
  frontend:
    image: ghcr.io/reazndev/purbank-web-frontend:latest
    container_name: purbank-frontend
    ports:
      - "80:80"
    networks:
      - purbank-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-https://ebanking.purbank.ch/api/v1}

networks:
  purbank-network:
    driver: bridge
