services:
  frontend:
    image: ghcr.io/reazndev/purbank-web-frontend:latest
    container_name: purbank-frontend
    ports:
      - "80:80"
    networks:
      - purbank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  purbank-network:
    driver: bridge