# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Angular Build

# {1} On PR/Push to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2} Checkout source code
      - name: Checkout the source code
        uses: actions/checkout@v4

      # {3} Define runtime for pipeline
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}          
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {4} Install dependencies
      - name: Install dependencies
        run: npm ci
      # {5} Add tests later when we have them 
      # - name: Run tests
      #  run: npm run test:ci
      # {6} Build it :)
      - name: Build
        run: npm run build
